CXX = g++
CC = g++

all:		avg med percision size_unsigned_test

test:		all
	./avg <../data/single_grade
	./med <../data/single_grade

clobber:
	rm -f *.o *.exe core avg med percision size_unsigned_test
