CXX = g++
CC = g++

all:	template_string_as_parameter

template_string_as_parameter:	template_string_as_parameter.o
template_string_as_parameter.o:	template_string_as_parameter.cpp template_string_as_parameter.h


clobber:
	rm -f *.o *.exe core
